name: clang-tidy

on: push

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgl-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev libxext-dev clang clang-tidy bear

      - name: Generate compile_commands.json
        run: bear -- make build

      - name: Run clang-tidy
        run: |
          clang-tidy -p . src/*.c --warnings-as-errors \
            --checks=-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*
